"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { BrainRadarChart } from "@/components/BrainRadarChart";
import { RegionCard } from "@/components/RegionCard";
import { RecommendationPanel } from "@/components/RecommendationPanel";
import { Headline } from "@/components/Headline";
import { Button } from "@/components/ui/button";
import { ExternalLink, Loader2 } from "lucide-react";
import { getSharedProject } from "@/lib/api";
import type { SharedProject, BrainScores } from "@/types/analysis";

export default function SharedProjectPage() {
  const params = useParams<{ token: string }>();
  const router = useRouter();
  const [data, setData] = useState<SharedProject | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!params?.token) return;
    getSharedProject(params.token)
      .then(setData)
      .catch((e) => setError(e instanceof Error ? e.message : "Not found"));
  }, [params?.token]);

  if (error) {
    return (
      <main className="min-h-screen flex flex-col items-center justify-center px-4 py-16">
        <p className="text-sm text-muted-foreground mb-4">This share link is invalid or expired.</p>
        <Button variant="outline" size="sm" onClick={() => router.push("/")}>
          Open NeuroPulse
        </Button>
      </main>
    );
  }

  if (!data) {
    return (
      <main className="min-h-screen flex items-center justify-center text-muted-foreground">
        <Loader2 className="w-4 h-4 animate-spin mr-2" />
        Loading…
      </main>
    );
  }

  const { result } = data;
  const keys = Object.keys(result.scores) as (keyof BrainScores)[];
  const avg = Math.round(Object.values(result.scores).reduce((a, b) => a + b, 0) / keys.length);

  return (
    <main className="min-h-screen px-4 py-10 max-w-4xl mx-auto">
      <div className="flex items-center justify-between gap-3 mb-8 flex-wrap">
        <div>
          <p className="text-xs uppercase tracking-wide text-muted-foreground font-medium">Shared analysis</p>
          <h1 className="text-2xl font-bold mt-0.5">{data.name}</h1>
        </div>
        <Button variant="outline" size="sm" onClick={() => router.push("/")}>
          <ExternalLink className="w-4 h-4 mr-1" /> Try NeuroPulse
        </Button>
      </div>

      <Headline text={result.headline} />

      <div className="grid md:grid-cols-2 gap-8 mb-8">
        <div>
          <h2 className="text-2xl font-bold mb-1">Brain Activation</h2>
          <p className="text-muted-foreground text-sm mb-4">
            Overall: <span className="font-semibold text-foreground">{avg}/100</span>
            <span className="ml-2 capitalize text-xs">({result.type})</span>
          </p>
          <BrainRadarChart scores={result.scores} />
        </div>
        <div className="space-y-2">
          <h3 className="font-semibold mb-3">Region Breakdown</h3>
          {keys.map((k) => <RegionCard key={k} regionKey={k} score={result.scores[k]} />)}
        </div>
      </div>

      <RecommendationPanel recommendations={result.recommendations} />

      <p className="text-xs text-muted-foreground text-center mt-12">
        Generated by NeuroPulse — open-source brain-response analysis for marketing content.
      </p>
    </main>
  );
}
